#############################################
# Set up configuration
#############################################
[metadata]
name = PhenoMicrobiome
version = 0.0.1
description = a package for prioritizing microbial features associated with host phenotype
long_description = file: README.md
long_description_content_type = text/markdown

url = https://github.com/Chengyao-Peng/PhenoMicrobiome
author = Chengyao Peng
author_email = "Chengyao Peng" <pppchengyao@gmail.com>

license = MIT
license_file = LICENSE


classifiers =
    Lisence :: OSI Approved :: MIT License
    Programming Language :: Python
    Programming Language :: Python :: 3.9
    Operating System :: OS Independent
    Topic :: Scientific/Engineering :: Bio-Informatics

keywords =
    Microbiome
    Host phenotype
    Bioinformatics
    Regression


[options]
# where is my code
package_dir =
    =src
packages = find:
include_package_data = True

[options.packages.find]
where = src



